name: serializer
description: Serialization to JSON using reflectable or codegen
version: 0.6.0
authors:
  - Hadrien Lejard <hadrien.lejard@gmail.com>
  - Stéphane Este-Gracias <sestegra@gmail.com>

homepage: https://github.com/dartsome/serializer

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  bson: ^0.2.0
  build_runner: ^0.3.0+1
  source_gen: ^0.5.4+2

dev_dependencies:
  test: ^0.12.0
  browser: ^0.10.0

transformers:
  - test/pub_serve:
      $include:
        - test/reflectable/*_test{.*,}.dart
        - test/codegen/*_test{.*,}.dart
  - $dart2js:
      minify: false

