name: serializer
description: Serialization to JSON using reflectable
version: 0.1.5
author: Walletek <hadrien.lejard@gmail.com>
homepage: https://github.com/walletek/serializer

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  reflectable: ">=0.5.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'