name: serializer_generator
description: Serialization to JSON using source_gen
version: 0.7.1+1
authors:
  - Hadrien Lejard <hadrien.lejard@gmail.com>
  - Stéphane Este-Gracias <sestegra@gmail.com>

homepage: https://github.com/dartsome/serializer

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  analyzer: ^0.30.0+2
  build: ^0.10.0+1
  build_runner: ^0.4.0+3
  path: ^1.4.2
  serializer: ^0.7.0
  source_gen: ^0.7.1

dev_dependencies:
  browser: ^0.10.0+2
  bson: ^0.3.0
  test: ^0.12.24+2

#dependency_overrides:
#  serializer:
#    path: ../serializer

transformers:
  - test/pub_serve:
      $include:
        - test/*_test{.*,}.dart
  - $dart2js:
      minify: false