name: serializer
description: Serialization to JSON using source_gen
version: 0.8.0
authors:
  - Hadrien Lejard <hadrien.lejard@gmail.com>
  - Stéphane Este-Gracias <sestegra@gmail.com>

homepage: https://github.com/dartsome/serializer

environment:
  sdk: '>=2.0.0-dev.1.2 <2.0.0'

dependencies:
  bson: any