name: serializer
description: Serialization to JSON using source_gen
version: 0.7.1
authors:
  - Hadrien Lejard <hadrien.lejard@gmail.com>
  - Stéphane Este-Gracias <sestegra@gmail.com>

homepage: https://github.com/dartsome/serializer

environment:
  sdk: '>=1.24.0 <2.0.0'

#dependencies:
#  bson: ^0.3.0